### ISSUE TITLE
neobolt.exceptions.AuthError: The client is unauthorized due to authentication failure.

### ISSUE THREAD

**Issue by mkanand33** [neo4j-examples/paradise-papers-django#60]
after successfully resetting password in neo4j server and run the code python manage.py runserver --seings=paradise_papers_search.settings.dev , i got an error saying  "neobolt.exceptions.AuthError: The client is unauthorized due to authentication failure.". Should I do anything else in the neo4j server or in the Django project setting file. after installed the dependencies, i got some errors regarding neo4j. ?how can i solve this?

**Comment by whatSocks** [comment]
@mkanand33 this project has been updated, could you check again?
