### ISSUE TITLE
Add whitenoise for heroku static files

### ISSUE THREAD

**Issue by mariamera** [neo4j-examples/paradise-papers-django#8]
**Instructions:** 
https://github.com/codingforentrepreneurs/Guides/blob/master/all/Heroku_Django_Deployment_Guide.md

**Comment by oscarpolanco** [comment]
Hello @mariamera 
Is this already handle?

**Comment by mariamera** [comment]
@oscarpolanco Hey Oscar, they are on the settings file as well as the Procfile for heroku.
